export const VIDEO_JOB_REPOSITORY = Symbol('VIDEO_JOB_REPOSITORY');
export const SEGMENTATION_STRATEGY = Symbol('SEGMENTATION_STRATEGY');
export const FRAME_JOB_QUEUE = Symbol('FRAME_JOB_QUEUE');
export const SORA_CLIENT = Symbol('SORA_CLIENT');
export const VIDEO_ASSEMBLER = Symbol('VIDEO_ASSEMBLER');
export const REFERENCE_IMAGE_STORAGE = Symbol('REFERENCE_IMAGE_STORAGE');
export const PROGRESS_PUBLISHER = Symbol('PROGRESS_PUBLISHER');
