version: "3.9"

services:
  backend:
    build:
      context: ../../
      dockerfile: infra/docker/backend.Dockerfile
    environment:
      PORT: 4000
      FRONTEND_ORIGIN: http://localhost:3000
      DATABASE_URL: postgres://sora:sora@db:5432/sora
      SORA_API_KEY: ${SORA_API_KEY:-changeme}
      SORA_BASE_URL: https://api.openai.com/v1
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"
    volumes:
      - backend_storage:/app/storage

  frontend:
    build:
      context: ../../
      dockerfile: infra/docker/frontend.Dockerfile
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:4000/api
      NEXT_PUBLIC_WS_BASE_URL: http://localhost:4000
    ports:
      - "3000:3000"
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: sora
      POSTGRES_USER: sora
      POSTGRES_PASSWORD: sora
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  backend_storage:
  db_data:
